### PR TITLE
Adds testcase for credhub

### PR DESCRIPTION
**Pull request by TisVictress**
[#163091748]
[#163089547]

Signed-off-by: Victoria Henry <vhenry@pivotal.io>

Thanks for submitting a PR to B-DRATS.

## Checklist

Please provide the following information:

- [CredHub ] What component are you testing?
- [Yes] Have you created a `TestCase` and added it to the list of cases to be run?
- [Yes] Have you added an `include_<testcase-name>` property and any other new properties to the sample integration_config.json in the README?
- [Yes. 5.4.0-891ff634-2018-11-14T00:21:14Z ] Have you manually validated your `TestCase` against a deployed BOSH? If so, which version?
- [No ] Does this change rely on a particular version of a release?
- [Yes] Are you available for a cross-team pair to help troubleshoot your PR?
- [Yes: https://github.com/cloudfoundry/bosh-deployment/pull/343] Have you submitted a pull request to modify the bosh-deployment [backup and restore opsfile](https://github.com/cloudfoundry/bosh-deployment/blob/master/bbr.yml) to add a backup job and properties where appropriate?

### Do you have any other useful information for us?

We're on the #bbr cloudfoundry Slack channel if you need us.

### CODE REVIEW

**Comment by TisVictress** [comment]
@aclevername Is there anything we can do to get this through?  Let me know.

**Comment by aclevername** [comment]
Sorry for the delay @TisVictress, we were having some CI problems. Running it through now :)

**Comment by aclevername** [comment]
Hi @TisVictress the PR is currently failing in CI for the following reason:

```
Failed to compile acceptance:

# github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/acceptance
package github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/acceptance_test
	imports github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/testcases
	imports code.cloudfoundry.org/credhub-cli/credhub: cannot find package "code.cloudfoundry.org/credhub-cli/credhub" in any of:
	/tmp/build/02a90028/src/github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/vendor/code.cloudfoundry.org/credhub-cli/credhub (vendor tree)
	/usr/local/go/src/code.cloudfoundry.org/credhub-cli/credhub (from $GOROOT)
	/tmp/build/02a90028/src/code.cloudfoundry.org/credhub-cli/credhub (from $GOPATH)
FAIL	github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/acceptance [setup failed]
```

**Comment by aclevername** [comment]
Hi @TisVictress we are also seeing failures in our master branch (without this PR changes) were credhub is failing because of this issue https://github.com/pivotal-cf/credhub-release/issues/31 . So we won't be able to merge this PR until the bug mentioned in the comment before and this git issue is resolved.

**Comment by aclevername** [comment]
Hey @TisVictress any updates?

**Comment by alamages** [comment]
The work of this PR is being continued on a new PR: https://github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/pull/12. Let's follow up the progress there. I am closing this.

**Pull request closed without merging**
