### PR TITLE
Add BOSH testcases

### PR DESCRIPTION
**Pull request by luan**
Hi!

We (the BOSH team) are in the process of migrating our current [`bbr` tests](https://github.com/cloudfoundry/bosh/blob/master/src/go/src/github.com/cloudfoundry/bosh-release-acceptance-tests/bbr/bbr_test.go) to B-DRATs instead.
This PR is meant as a conversation starter and a more concrete form of feedback on B-DRATs. We'd love to pair on this soon-ish to discuss further. But some things we learned:

Our tests do more dramatic disasters which weren't possible on B-DRATs:
 * completely obliterate the director and the VMs on the IaaS
 * completely obliterate the director DB and blobstore (keeping VMs around)

The multiple test cases paradigm didn't fit our needs. Our disaster definitions affect the environment more globally making it very difficult to run more than one scenario at a time.
For that reason we made the runner serial, which isn't exactly what we wanted to do, but was a small enough adaptation to make it fit our needs. We were toying with the idea of having separate definitions for testcases and disaster types, so that you can cross-check testcases with multiple disaster scenarios.

## Checklist

- [X] What component are you testing? _BOSH_
- [X] Have you created a `TestCase` and added it to the list of cases to be run?
- [X] Have you added an `include_<testcase-name>` property and any other new properties to the sample integration_config.json in the README?
- [X] Have you manually validated your `TestCase` against a deployed BOSH? If so, which version? _268.3_
- [ ] Does this change rely on a particular version of a release? _No_
- [X] Are you available for a cross-team pair to help troubleshoot your PR?
- [ ] Have you submitted a pull request to modify the bosh-deployment [backup and restore opsfile](https://github.com/cloudfoundry/bosh-deployment/blob/master/bbr.yml) to add a backup job and properties where appropriate? _No_

### CODE REVIEW

**Comment by aclevername** [comment]
Hi @luan 

Thanks for the PR, we will spend some time looking into your proposed changes. We've added a story [here](https://www.pivotaltracker.com/story/show/162865783) to track our investigation.

Thanks,
Jake

**Comment by aclevername** [comment]
As part of adding the `stemcell_path` config we have had to update our CI to take in a stemcell so we have made a commit to your branch to add that as an input, this should allow us to run the PR in CI.

**Comment by aclevername** [comment]
Hi @luan 

Thanks for the PR. I've taken the time run and look over the test cases and I have a few questions.

First of all I just want to clarify the value-add of the two new test cases `clean_up_testcase` and `truncate_db_blobstore_testcase`. 

From looking into the `clean_up_testcase` it appears that it only differs to the `deployment_testcase` by removing the stemcell/releases after backup and then re-uploading the stemcell after restoring. I was wondering what exactly this is testing? The only behaviour change from BOSH that I can see is that it asserts that BOSH knows how to act when it has an entry for a stemcell its in DB but no corresponding file in the blobstore.

The `truncate_db_blobstore_testcase` is quite different to the other two test cases and I can see that it is valuable to test the the director restore works into what is essentially a new director. Am I correct in thinking that this test case addresses your second comment about `completely obliterate the director DB and blobstore (keeping VMs around)`?

You also mentioned about the change from running these tests in parallel to serial, given these new tests cases added I think that makes a lot of sense, thanks for making the change.

I have managed to get all three test cases running in CI and passing, but I believe there might be a bug in the new `serial_runner`. When running the suite it prints that its running the `clean_up_testcase` for everytestcases, I'm not quite sure what is causing this. I've attached an example output, if you search for `clean_up_testcase` you should see it being printed in other test cases. I would appreciate if this could be fixed before the PR is merged.
[CI output.txt](https://github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/files/2726663/CI.output.txt) 

Also I wanted to make a suggestion to rename `stemcell_path` to `stemcell_src` or something similar to indicate that you can pass in a download url instead of a path, due to the setup of our CI and the way in which ginkgo runs suites we have had problems getting relative or absolute paths to the stemcell image in CI, we are instead using the [stemcell resource](https://github.com/concourse/bosh-io-stemcell-resource) to pull the latest download url and are populating that into the config.

Finally you mentioned wanting to add other test cases that are currently not feasible with the currently B-DRATs setup `completely obliterate the director and the VMs on the IaaS,
completely obliterate the director DB and blobstore (keeping VMs around)`. These sound like interesting additions and would require a big change, mainly because of adding the utility to talk directly to the IaaS. I think its worth having a chat about this, after you've had a chance to read through the above feel free to reach out to us on slack [in the #bbr channel](https://cloudfoundry.slack.com/messages/C6D6N3PBL/?)

Thanks,
Jake

**Comment by luan** [comment]
Hi @aclevername,

> From looking into the clean_up_testcase it appears that it only differs to the deployment_testcase by removing the stemcell/releases after backup and then re-uploading the stemcell after restoring. I was wondering what exactly this is testing? The only behaviour change from BOSH that I can see is that it asserts that BOSH knows how to act when it has an entry for a stemcell its in DB but no corresponding file in the blobstore.

It doesn't really need to be a separate test, we merely didn't want to make changes to your existing test case. We think it's valuable to run `clean-up` though to ensure we're re-populating the blobstore with releases. It also helps make obvious a kind of unfortunate workflow which is the operator having to re-upload the stemcell manually.

> The truncate_db_blobstore_testcase is quite different to the other two test cases and I can see that it is valuable to test the the director restore works into what is essentially a new director. Am I correct in thinking that this test case addresses your second comment about completely obliterate the director DB and blobstore (keeping VMs around)?

I'd say it simulates it well enough.

> I have managed to get all three test cases running in CI and passing, but I believe there might be a bug in the new serial_runner. When running the suite it prints that its running the clean_up_testcase for everytestcases, I'm not quite sure what is causing this. I've attached an example output, if you search for clean_up_testcase you should see it being printed in other test cases. I would appreciate if this could be fixed before the PR is merged.

Not sure I had run into anything like it before, but it's possible we need a local closure variable for the test case [here](https://github.com/cloudfoundry-incubator/bosh-disaster-recovery-acceptance-tests/pull/6/files#diff-0fc3397759969f7d7ae7916ca4ca5401R19).

> Also I wanted to make a suggestion to rename stemcell_path to stemcell_src or something similar to [...]

This sounds fine with me.

And finally, I'd love to have a chat about the missing test cases that would `completely obliterate the director`.

I also realized while reviewing this that we don't have any tests that use persistent disks. I remember trying to add them and running into trouble because restoring it wasn't the same as restoring a regular deployment (the `cck` commands were different). So it might be good to talk about that use case as well.

**Comment by aclevername** [comment]
Thanks for the reply @luan , 

To summarise whats left to do:
- Merge cleanup and deployment test into one
- Fix bug with serial test runner
- Rename stemcell_path to stemcell_src
- Have a chat about further test cases and persistent disks.

I have reached out to you on slack for a meeting

Thanks,
Jake

**Comment by xtreme-andrew-su** [comment]
> When running the suite it prints that its running the clean_up_testcase for everytestcases, I'm not quite sure what is causing this.

The issue with this seems like the way the tests are being generated. Looks like the `testCase` variable in the for loop is referenced in a way that it uses the last value. This means the tests are only really testing the cleanup scenario 3 times.

**Comment by dpb587-pivotal** [comment]
We've updated the tests to combine deploy/clean-up, renamed the stemcell variable, and fixed the serial runner bug. We tried them out locally.

Please let us know if you have more feedback on this.

**Comment by aclevername** [comment]
Thanks for the update @dpb587-pivotal @xtreme-andrew-su , the PR looks good, it has gone green in CI and is ready to merge. We are going to make one minor change to suppress the printing of the monit output as it is producing a large amount of text. Once we have made that change we will accept the PR.

Thanks,
Jake & @MModhaPivotal

**Comment by aclevername** [comment]
Merged. Thanks @dpb587-pivotal @luan @xtreme-andrew-su

**Pull request merged**
